version: 2

jobs:
  build: 
    docker:
      - image: circleci/python:3.7

    working_directory: ~/devops2

    steps:
      # 1 Obtain the repo from GitHub 
      - checkout
      
      - run: 
          name: install flake8 
          command: | 
            python3 -m venv venv 
            . venv/bin/activate
            pip install flake8 

      # 2 Create virtual environment and install dependecies 
      - run: 
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            #pip install --upgrade pip
            #pip install pytest-cov
      
      # 3 Run coding convention software and also the tester 
      - run: 
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=env --statistics
            pytest --junitxml=test-results/junit.xml

      - store_test_results:
            path: test-results  

      - store_artifacts:
            path: test-results
